# action.yml
name: 'chain-smoker test execution'
description: 'Executes chain-smoker in given directory'
branding:
  icon: 'check-square'
  color: 'purple'

inputs:
  directory:
    description: 'The directory to run in.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.directory }}
