# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: detect-private-key
    -   id: double-quote-string-fixer
    -   id: name-tests-test
        args: ["--django"]
    -   id: requirements-txt-fixer
    -   id: debug-statements
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-merge-conflict
    -   id: check-ast
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
        - id: flake8
exclude: |
        (?x)^(
            tests/parser/fixtures/unpacked-response.html|
            tests/parser/fixtures/gzipped-response.html|
        )$
