name: Build proxy

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v4
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Go Release Binaries
      uses: wangyoucao577/go-release-action@v1.46
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
        project_path: parser/proxy
        binary_name: proxy-${{ steps.date.outputs.date }}
        release_tag: proxy
