name: Test branch action

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Action step
      env:
        bar: baz
      uses: philsupertramp/chain-smoker/action@v1
      with:
        directory: 'examples'
