name: Test branch action

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Action step
      uses: philsupertramp/chain-smoker/action@${{ github.sha }}
      with:
        directory: 'examples'
